export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export XDG_CACHE_HOME=~/.cache

setopt auto_cd multios prompt_subst promptsubst
setopt auto_pushd pushd_ignore_dups pushdminus

autoload -Uz colors && colors

autoload -Uz select-word-style
select-word-style shell

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

source "$HOME/.aliases"

# Composer
# if [[ -x "$(command -v composer)" ]]; then
#     export PATH=$PATH:$HOME/.composer/vendor/bin
# fi
# Homebrew
export PATH=.:./vendor/bin:./node_modules/.bin:$PATH
# Golang
export GOPATH="$HOME/go"

source "$HOME/.zinit"

#source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
